[package]
distribution = "2201.11.0-20241218-101200-109f6cc7"
org = "ballerinax"
name = "aws.dynamodb"
version = "@toml.version@"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.dynamodb"
keywords = ["Communication/Email", "Cost/Free", "Vendor/AWS", "Area/Databases", "Type/Connector"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
